---
tags: [spring-cloud, ribbon]
projects: [spring-cloud, spring-cloud-netflix]
---
:spring_version: current
:spring_boot_version: 1.5.2.RELEASE
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-client-side-load-balancing
本指南会带你走一遍使用 Netflix Ribbon 为微服务应用提供客户端负载均衡的过程。

== 你将做出什么

你会构建一个在调用另一个微服务应用的时候使用Netflix Ribbon和Spring Cloud Netflix提供客户端负载均衡的微服务应用。

== 你需要什么

:java_version: 1.8
include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[reveal-gradle]]
[.reveal-gradle]
== 使用Gradle构建

[[scratch]]
[.use-gradle]
== 使用Gradle构建

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/build_system_intro.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/create_directory_structure_hello.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/create_both_builds.adoc[]

`say-hello/build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::initial/say-hello/build.gradle[]
----

`user/build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::initial/user/build.gradle[]
----

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/spring-boot-gradle-plugin.adoc[]

[[reveal-maven]]
[.reveal-maven]
== 使用Maven构建

[[use-maven]]
[.use-maven]
== 使用Maven构建

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/build_system_intro_maven.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/create_directory_structure_hello.adoc[]

`say-hello/pom.xml`
[source,xml]
----
include::initial/say-hello/pom.xml[]
----

`user/pom.xml`
[source,xml]
----
include::initial/user/pom.xml[]
----

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/spring-boot-maven-plugin.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/hide-show-sts.adoc[]



[[initial]]
== 编写服务器服务

我们的 &#8220;服务器&#8221; 服务就是说你好。它将返回一个随机问候语（从三个静态列表中挑选出来），从可访问的端点 `/greeting` 返回。

在 `src/main/java/hello`, 创建一个文件 `SayHelloApplication.java`. 它应该看起来像这样:

`say-hello/src/main/java/hello/SayHelloApplication.java`
[source,java]
----
include::complete/say-hello/src/main/java/hello/SayHelloApplication.java[]
----

`@RestController` 注解和一起使用`@Controller` 与 `@ResponseBody` 的效果是一样的. 它标志着 `SayHelloApplication` 作为一个控制器类（就像 `@Controller` 做的一样）并确保返回值类的 `@RequestMapping` 方法将自动转换为适当的类型，从原来直接写入响应体（就像 `@Controller` 做的一样）。我们有一个 `@RequestMapping` 方法生成 `/greeting` 然后另一个方法生成根路径 `/` 。（当我们稍后开始使用Ribbon的时候，我们会想要第二种方法。）

我们要在本地运行该应用程序的多个实例的本地与客户服务应用，所以我们来创建目录 `src/main/resources` ，在里面创建文件 `application.yml` ，然后在那个文件，为 `server.port` 设置一个默认值 。（我们还将指示应用程序的其他实例在其他端口上运行，这样当我们运行时，没有一个说hello实例会与客户端发生冲突）。当我们在修改这个文件中的时候，我们也可以为我们的服务设置 `spring.application.name` 。

`say-hello/src/main/resources/application.yml`
[source,yaml]
----
include::complete/say-hello/src/main/resources/application.yml[]
----

== 从客户端服务访问

我们用户将看到这个用户应用。它会访问说“hello”的应用程序以获得问候，然后当用户访问 `/hi` 端点时，将其发送给我们的用户。

在用户应用程序目录，在 `src/main/java/hello`，添加文件 `UserApplication.java` ：

`user/src/main/java/hello/UserApplication.java`
[source,java]
----
package hello;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;

@SpringBootApplication
@RestController
public class UserApplication {

  @Bean
  RestTemplate restTemplate(){
    return new RestTemplate();
  }

  @Autowired
  RestTemplate restTemplate;

  @RequestMapping("/hi")
  public String hi(@RequestParam(value="name", defaultValue="Artaban") String name) {
    String greeting = this.restTemplate.getForObject("http://localhost:8090/greeting", String.class);
    return String.format("%s, %s!", greeting, name);
  }

  public static void main(String[] args) {
    SpringApplication.run(UserApplication.class, args);
  }
}
----

为了从说 "Hello" 的应用中获得问候，我们用的是Spring的 `RestTemplate` 模板类。 `RestTemplate` 使HTTP GET来请求我们提供的说 "Hello" 服务的URL，并返回一个 `String` 作为结果。（欲了解更多关于使用Spring使用REST式服务的信息，请参见下面的 https://spring.io/guides/gs/consuming-rest/[Consuming a RESTful Web Service] 指南）。

添加 `spring.application.name` 和 `server.port` 属性到 `src/main/resources/application.properties` 或者 `src/main/resources/application.yml`:

`user/src/main/resources/application.yml`
[source,yaml]
----
spring:
  application:
    name: user

server:
  port: 8888
----

== 跨服务器实例的负载平衡

现在我们可以在用户服务上访问 `/hi` ，看到一个友好的问候语：

----
$ curl http://localhost:8888/hi
Greetings, Artaban!

$ curl http://localhost:8888/hi?name=Orontes
Salutations, Orontes!
----

为了跨越一个硬编码的服务器URL到一个负载均衡的解决方案，让我们设置Ribbon。在 `application.yml` 文件下 `user/src/main/resources/` ，添加以下属性:

`user/src/main/resources/application.yml`
[source,yaml]
----
say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000
----

这种配置属性在Ribbon _client_ 中。Spring Cloud Netflix为我们每一个在我们应用中的Ribbon Client创造一个 `ApplicationContext` 。这用于给客户端提供一组用于Ribbon组件实例的bean，包括：

* `IClientConfig`, 用于为客户端或负载均衡器存储客户端配置,
* `ILoadBalancer`, 表示软件负载均衡器,
* `ServerList`, 它定义了如何获取服务器列表,
* `IRule`, 描述负载平衡策略，以及
* `IPing`, 这说的如何进行定期ping服务器。

在我们上面的例子中，客户端被命名为 `say-hello`。我们设置的属性 `eureka.enabled` （这个属性我们设置为 `false` ）， `listOfServers`，和 `ServerListRefreshInterval` 。Ribbon中的负载平衡器通常从从Netflix Eureka服务注册中获取他们的服务器列表。（看https://spring.io/guides/gs/service-registration-and-discovery/[服务注册与发现]指南信息使用Spring Cloud 注册Eureka服务。）这里为了我们简单的目的，我们跳过 Eureka ，所以我们设置 `ribbon.eureka.enabled` 属性为 `false` 而不是给Ribbon 一些静态的` listofservers `。 `ServerListRefreshInterval` 是刷新Ribbon服务列表的间隔时间，以毫秒为单位。

在我们的 `UserApplication` 类中, 切换 `RestTemplate` 使用Ribbon客户端到服务器地址问好：

`user/src/main/java/hello/UserApplication.java`
[source,java]
----
include::complete/user/src/main/java/hello/UserApplication.java[]
----

我们做了一对关联其他相关变化的 `UserApplication` 类。我们的 `RestTemplate` 现在也标记为 `LoadBalanced` ；这告诉Spring Cloud，我们想利用其负载均衡的支持（在这种情况下，用Ribbon提供）。这个类使用`@RibbonClient`注释 我们给客户一个 `name`  (`say-hello`)然后另一个类，它包含额外的客户端 `configuration`。

我们需要创建这个类。在 `user/src/main/java/hello` 目录下添加一个新文件 `SayHelloConfiguration.java`:

`user/src/main/java/hello/SayHelloConfiguration.java`
[source,java]
----
include::complete/user/src/main/java/hello/SayHelloConfiguration.java[]
----

我们可以通过创建具有相同名称的bean来覆盖Spring Cloud Netflix给我们的任何与Ribbon相关的bean。在这里，我们重写 `IPing` 和默认负载平衡器使用 `IRule`。默认 `IPing` 是 `NoOpPing` （这实际上不ping服务器实例，而不是总是报道他们稳定），和默认的`IRule`是 `ZoneAvoidanceRule` （避免了亚马逊的EC2区最有可能出故障的服务器，因此可能会有点难在我们本地环境尝试）。

我们的 `IPing` 是 `PingUrl` ，将ping URL来检查每个服务器的状态。你可能还记得Say Hello会映射到 `/` 路径的方法；这意味着Ribbon ping 一个正在运行着 Say Hello 的服务器时将得到一个HTTP 200响应。我们`建立的 `IRule` ,也就是  `AvailabilityFilteringRule` ，将使用Ribbon内置断路器功能，过滤掉任何处于 &#8220;open-circuit&#8221; 状态的服务器：如果一个ping未能连接到指定的服务器，或者如果它被读取故障服务器，Ribbon将考虑到让服务器 &#8220;dead&#8221; ,直到它开始正常的反应。

[NOTE]
====
`@SpringBootApplication` 注解在 `UserApplication` 类相当于（其中包括） `@Configuration` 注解将类标记作为一个源的bean定义。这就是为什么我们不需要注释的 `SayHelloConfiguration` 类 `@Configuration` ：因为它在同一个包中有一个 `UserApplication` 类，它已经被扫描成为生产bean的方法。

这种方法意味着我们Ribbon的配置将主要应用上下文的一部分，因此我们应用中的 _所有_ Ribbon 客户端都会共享。在一个正常的应用程序，你可以通过让Ribbon bean从主应用程序上下文脱离避免这种情况（例如，在这个例子中，你可以把 `SayHelloConfiguration` 放在和 `UserApplication` 不同的包中）。
====

== 试一下

运行 Say Hello 服务，使用的是Gradle

----
$ ./gradlew bootRun
----

或者 Maven:

----
$ mvn spring-boot:run
----

运行在端口9092和9999的其他实例，再利用Gradle：

----
$ SERVER_PORT=9092 ./gradlew bootRun
----

或者 Maven:

----
$ SERVER_PORT=9999 mvn spring-boot:run
----

然后启动用户服务。访问 `localhost:8888/hi` 然后看 Say Hello 服务实例。你可以看到Ribbon的每间隔15秒扫描：

----
2016-03-09 21:13:22.115  INFO 90046 --- [nio-8090-exec-1] hello.SayHelloApplication                : Access /
2016-03-09 21:13:22.629  INFO 90046 --- [nio-8090-exec-3] hello.SayHelloApplication                : Access /
----

您对用户服务的请求将导致调用以循环形式在正在运行的实例之间传播：

----
2016-03-09 21:15:28.915  INFO 90046 --- [nio-8090-exec-7] hello.SayHelloApplication                : Access /greeting
----

现在关闭一个Say Hello的服务器实例。一旦Ribbon已经ping不通一个实例，认为他已经宕机了，你应该看到请求开始在其他实例上保持平衡。

== 总结

祝贺你!您刚刚开发了一个Spring应用程序，它为调用另一个应用程序执行客户端负载平衡。



include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/footer.adoc[]

